import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      // Generated by wasm-pack.
      'public/wasm/**',
      'public/wasm-viewer/**',
      'public/wasm-kitchen/**',
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  // Keep last: turns off every rule that would fight Prettier.
  ...compat.extends('prettier'),
];

export default eslintConfig;
